Implementing DMN
AgileKip/akip-core-community pull request #36
Opened 2023-07-31 16:10 UTC by CassioJr

2023-08-09 20:22 UTC, CassioJr commented on src/main/resources/config/liquibase/changelog/20230222000002_added_entity_DecisionDeployment.xml
> +    <changeSet id="20230222000002-1" author="cassiojr" context="dev or prod">
Resolved, context="dev or prod" is unnecessary

2023-08-09 20:24 UTC, utelemaco commented on src/main/java/org/akip/domain/DecisionDefinition.java
> +    @OneToMany(mappedBy = "decisionDefinition")
Avoid this dependency. Why does the decisionDefinitiion need the deployments? You can remove it.

2023-08-10 17:06 UTC, utelemaco requested changes

2023-08-10 17:06 UTC, utelemaco commented on src/main/resources/config/liquibase/akip-master.xml
> +    <include file="config/liquibase/changelog/20230222000001_added_entity_DecisionDefinition.xml" relativeToChangelogFile="false"/>
@CassioJr, I forgot to mention: in the `akip-master.xml` file, the changesets are not ordered by date. Instead, we use a sequence order. So, to keep the pattern, the new changesets should start with `000..14`..`000...15`

2023-08-19 05:14 UTC, merged